site_name: PlotNado Documentation
nav:
  - Home: index.md
  - Reference: reference.md
  - Aesthetics: aesthetics.md
  - CLI: cli.md
  - Changelog: changelog.md

theme:
  name: mkdocs
  logo: assets/plotnado-logo.svg
  favicon: assets/plotnado-logo.svg
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight:
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mkdocs-click
  - admonition
  - codehilite:
      guess_lang: false

plugins:
  - search
  - mkdocs-jupyter:
      include:
        - "*.ipynb"
      execute: false

hooks:
  - scripts/mkdocs_hooks.py

repo_url: https://github.com/alsmith151/plotnado

validation:
  nav:
    omitted_files: ignore
