site_name: PlotNado Documentation
nav:
  - Home: index.md
  - Track Aliases: track_aliases.md
  - Tutorials:
    - Basic Usage: basic_example.ipynb
    - Simple Overlays: simple_overlays.ipynb
  - API Reference: api_reference.md
  - Aesthetics Reference: aesthetics_reference.md
  - Changelog: changelog.md
  - Reference Summary: reference/SUMMARY.md

theme:
  name: mkdocs
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight:
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mkdocs-click
  - admonition
  - codehilite:
      guess_lang: false

plugins:
  - search
  - mkdocstrings
  - literate-nav:
      nav_file: SUMMARY.md
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocs-jupyter

repo_url: https://github.com/alsmith151/plotnado