from __future__ import annotations

from pathlib import Path
from typing import Any, Self

import matplotlib.figure
import pandas as pd

from .tracks.enums import (
    BigWigDiffMethod,
    CollectionStyle,
    CoolerTransform,
    DataRangeStyle,
    DisplayMode,
    FontWeight,
    GeneLabelOverlapStrategy,
    GeneLabelStyle,
    NarrowPeakColorBy,
    PlotStyle,
    Position,
)
from .theme import BuiltinTheme, Theme
from .tracks import GenomicRegion, Track


class GenomicFigure:
    def __init__(
        self,
        tracks: list[Track] | None = ...,
        width: float = ...,
        track_height: float = ...,
        theme: Theme | BuiltinTheme | str | None = ...,
    ) -> None: ...

    def add_track(self, track: str | Track, **kwargs: Any) -> Self: ...

    def bigwig(self, data: Any, /, *,
            title: str | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            y_min: float | None = None,
            y_max: float | None = None,
            style: PlotStyle = PlotStyle.STD,
            color: str = '#2171b5',
            fill: bool = True,
            alpha: float = 0.9,
            linewidth: float = 0.8,
            scatter_point_size: float = 1.0,
            show_baseline: bool = True,
            baseline_color: str = '#b8bec8',
            baseline_alpha: float = 0.85,
            baseline_linewidth: float = 0.6,
            smoothing_window: int = 1,
            smoothing_method: Literal['mean', 'median'] = 'mean',
            smoothing_center: bool = True,
            min_value: float | None = None,
            max_value: float | None = None,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def genes(self, genome: str = ..., /, *,
            title: str | None = None,
            data: Path | str | DataFrame | None = None,
            height: float = 1.5,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            row_scale: float = 1.0,
            small_relative: float = 0.01,
            gene_count: int = 0,
            style: PlotStyle = PlotStyle.STD,
            color: str = 'black',
            fill: bool = True,
            alpha: float = 1.0,
            display: DisplayMode = DisplayMode.COLLAPSED,
            minimum_gene_length: int = 0,
            max_number_of_rows: int = 4,
            interval_height: float = 0.1,
            arrow_size: float = 0.12,
            exon_linewidth: float = 0.8,
            exon_edge_color: str = 'black',
            exon_color: str = 'black',
            intron_linewidth: float = 0.5,
            intron_color: str = 'black',
            chevron_height_ratio: float = 0.22,
            chevron_vertical_offset_ratio: float = 0.0,
            chevron_width_fraction: float = 0.035,
            chevron_min_width_bp: float = 40.0,
            chevron_margin_bp: float = 20.0,
            chevron_target_spacing_bp: float = 9000.0,
            chevron_max_count: int = 10,
            gene_label_font_size: int = 10,
            gene_label_style: GeneLabelStyle = GeneLabelStyle.ITALIC,
            show_labels: bool = True,
            label_overlap_strategy: GeneLabelOverlapStrategy = GeneLabelOverlapStrategy.AUTO,
            label_max_chars: int = 20,
            label_offset_fraction: float = 0.005,
            label_stagger_offset: float = 0.15,
            label_vertical_offset: float = 0.14,
            label_min_overlap_bp: int = 200,
            label_min_overlap_fraction: float = 0.15,
            label_connectors: bool = False,
            label_connector_linewidth: float = 0.7,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def axis(self, *,
            title: str = '',
            data: Any | None = None,
            height: float = 0.2,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            show_chromosome: bool = False,
            color: str = '#666666',
            font_size: int = 9,
            num_ticks: int = 5,
            use_human_readable_labels: bool = False,
            tick_height: float = 0.15,
            axis_linewidth: float = 1.1,
            tick_color: str = '#333333',
            tick_linewidth: float = 0.9,
            chromosome_fontweight: FontWeight = FontWeight.BOLD,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def scalebar(self, *,
            title: str = 'ScaleBar',
            data: Any | None = None,
            height: float = 0.3,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            style: PlotStyle = PlotStyle.STD,
            color: str = '#333333',
            position: Position = Position.LEFT,
            scale_distance: float | None = None,
            font_size: int = 8,
            bar_linewidth: float = 1.8,
            tick_linewidth: float = 1.4,
            tick_height: float = 0.1,
            label_offset: float = 0.25,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def spacer(self, height: float = ..., /, *,
            title: str = '',
            data: Any | None = None,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def bed(self, data: Any, /, *,
            title: str | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = 'steelblue',
            edge_color: str = 'black',
            alpha: float = 0.78,
            interval_height: float = 0.45,
            display: DisplayMode = DisplayMode.COLLAPSED,
            max_rows: int = 5,
            show_labels: bool = False,
            label_field: str = 'name',
            font_size: int = 8,
            rect_linewidth: float = 0.7,
            draw_edges: bool = True,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def cooler(self, file: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 2.5,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            resolution: int | None = None,
            balance: bool = True,
            transform: CoolerTransform = CoolerTransform.NONE,
            cmap: str = 'RdBu_r',
            min_value: float | None = None,
            max_value: float | None = None,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def bigwig_collection(self, files: list[str], /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 2.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            colors: list[str] | None = None,
            labels: list[str] | None = None,
            alpha: float = 0.6,
            style: CollectionStyle = CollectionStyle.OVERLAY,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def bigwig_diff(self, file_a: str, file_b: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 1.5,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            method: BigWigDiffMethod = BigWigDiffMethod.SUBTRACT,
            positive_color: str = '#d62728',
            negative_color: str = '#1f77b4',
            linewidth: float = 0.7,
            bar_alpha: float = 0.45,
            zero_line_color: str = '#333333',
            zero_line_width: float = 0.6,
            zero_line_alpha: float = 0.8,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def bigwig_overlay(self, tracks: list[Any], /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 2.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            colors: list[str] | None = None,
            alpha: float = 0.5,
            show_labels: bool = True,
            min_value: float | None = None,
            max_value: float | None = None,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def overlay(self, tracks: list[Any], /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 2.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            colors: list[str] | None = None,
            alpha: float = 0.5,
            show_labels: bool = True,
            min_value: float | None = None,
            max_value: float | None = None,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def narrowpeak(self, data: Any, /, *,
            title: str | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = '#d95f02',
            edge_color: str = 'black',
            alpha: float = 0.78,
            interval_height: float = 0.28,
            display: DisplayMode = DisplayMode.COLLAPSED,
            max_rows: int = 5,
            show_labels: bool = False,
            label_field: str = 'name',
            font_size: int = 8,
            rect_linewidth: float = 0.7,
            draw_edges: bool = True,
            color_by: NarrowPeakColorBy | None = NarrowPeakColorBy.SIGNAL_VALUE,
            cmap: str = 'Oranges',
            min_score: float | None = None,
            max_score: float | None = None,
            show_summit: bool = True,
            summit_color: str = 'black',
            summit_width: float = 0.8,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def links(self, data: Any, /, *,
            title: str | None = None,
            height: float = 2.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = 'steelblue',
            edge_color: str | None = None,
            alpha: float = 0.55,
            linewidth: float = 0.8,
            cmap: str = 'viridis',
            max_height: float = 0.8,
            color_by_score: bool = False,
            min_score: float | None = None,
            max_score: float | None = None,
            y_baseline: float = 0.1,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def highlights(self, data: Any, /, *,
            title: str | None = None,
            height: float = 0.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = 'yellow',
            alpha: float = 0.3,
            edge_color: str | None = None,
            linewidth: float = 1.0,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def hline(self, y_value: float, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 0.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = 'red',
            linestyle: str = '--',
            linewidth: float = 1.0,
            alpha: float = 0.8,
            zorder: int = 10,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def vline(self, x_position: int | str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 0.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            color: str = 'red',
            linestyle: str = '--',
            linewidth: float = 1.0,
            alpha: float = 0.8,
            zorder: int = 10,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def quantnado_coverage(self, sample: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            quantnado: Any | None = None,
            dataset_path: str | None = None,
            coverage_data: Any | None = None,
            color: str = '#2171b5',
            alpha: float = 0.75,
            fill: bool = True,
            linewidth: float = 0.8,
            min_value: float | None = None,
            max_value: float | None = None,
            show_baseline: bool = True,
            baseline_color: str = '#b8bec8',
            baseline_alpha: float = 0.85,
            baseline_linewidth: float = 0.6,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def quantnado_stranded_coverage(self, sample: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            quantnado: Any | None = None,
            dataset_path: str | None = None,
            coverage_fwd_data: Any | None = None,
            coverage_rev_data: Any | None = None,
            color: str = '#1f78b4',
            reverse_color: str | None = None,
            alpha: float = 0.7,
            fill: bool = True,
            linewidth: float = 0.8,
            min_value: float | None = None,
            max_value: float | None = None,
            show_baseline: bool = True,
            baseline_color: str = '#444444',
            baseline_alpha: float = 0.8,
            baseline_linewidth: float = 0.6,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def quantnado_methylation(self, sample: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            quantnado: Any | None = None,
            dataset_path: str | None = None,
            methylation_variable: str = 'methylation_pct',
            methylation_data: Any | None = None,
            color: str = '#2a9d8f',
            alpha: float = 0.75,
            point_size: float = 10.0,
            min_value: float | None = 0.0,
            max_value: float | None = 100.0,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    def quantnado_variant(self, sample: str, /, *,
            title: str | None = None,
            data: Any | None = None,
            height: float = 1.0,
            autoscale_group: str | None = None,
            color_group: str | None = None,
            quantnado: Any | None = None,
            dataset_path: str | None = None,
            allele_depth_ref_variable: str = 'allele_depth_ref',
            allele_depth_alt_variable: str = 'allele_depth_alt',
            genotype_variable: str = 'genotype',
            fetch_genotype: bool = True,
            allele_depth_ref_data: Any | None = None,
            allele_depth_alt_data: Any | None = None,
            genotype_data: Any | None = None,
            het_color: str = '#1f77b4',
            hom_alt_color: str = '#d62728',
            alpha: float = 0.8,
            linewidth: float = 0.9,
            marker_size: float = 24.0,
            min_value: float | None = 0.0,
            max_value: float | None = 1.08,
            show_baseline: bool = True,
            baseline_color: str = '#444444',
            baseline_alpha: float = 0.75,
            baseline_linewidth: float = 0.6,
            plot_title: bool = True,
            plot_scale: bool = True,
            label_on_track: bool = False,
            data_range_style: DataRangeStyle = DataRangeStyle.TEXT,
            label_box_enabled: bool = True,
            label_box_alpha: float = 0.9,
            title_location: Position = Position.LEFT,
            title_height: float = 0.8,
            title_size: int = 10,
            title_color: str = '#333333',
            title_font: str = 'DejaVu Sans',
            title_weight: FontWeight = FontWeight.BOLD,
            scale_location: Position = Position.RIGHT,
            scale_height: float = 0.8,
            scale_precision: int = 2,
            scale_size: int = 9,
            scale_color: str = '#666666',
            scale_font: str = 'DejaVu Sans',
            scale_weight: FontWeight = FontWeight.NORMAL,
        ) -> Self: ...

    @classmethod
    def available_track_aliases(cls) -> dict[str, str]: ...

    @classmethod
    def track_options(cls, track: str | type[Track]) -> dict[str, dict]: ...

    @classmethod
    def track_options_markdown(cls, track: str | type[Track]) -> str: ...

    def autoscale(self, enable: bool = ...) -> Self: ...
    def autocolor(self, palette: str = ...) -> Self: ...
    def highlight(self, region: str | GenomicRegion) -> Self: ...
    def highlight_style(self, color: str | None = ..., alpha: float | None = ...) -> Self: ...

    def plot(
        self,
        region: str | GenomicRegion,
        show: bool = ...,
        extend: float | int | None = ...,
        **kwargs: Any,
    ) -> matplotlib.figure.Figure | None: ...

    def plot_gene(self, gene: str, extend: float = ..., **kwargs: Any) -> matplotlib.figure.Figure | None: ...

    def plot_regions(
        self,
        regions: list[str] | str,
        ncols: int = ...,
        **kwargs: Any,
    ) -> list[matplotlib.figure.Figure]: ...

    def to_toml(self, path: str) -> None: ...

    @classmethod
    def from_toml(cls, path: str) -> GenomicFigure: ...

    def save(
        self,
        path: str | Path,
        region: str | GenomicRegion,
        dpi: int = ...,
        **kwargs: Any,
    ) -> None: ...

    def __repr__(self) -> str: ...
    def _repr_html_(self) -> str: ...
