"""
Template model for representing genomic figure specifications in YAML format.

This module defines the structure for templates generated by the CLI init command
and used by the plot and validate commands. Templates are designed to be:
- Readable and editable by users
- Stable across validation and rendering
- Concise, avoiding internal implementation details
"""

from pathlib import Path
from typing import Any, Optional

import yaml
from pydantic import BaseModel, ConfigDict, Field

from .tracks.enums import TrackType


class TrackSpec(BaseModel):
    """Specification for a single track to be added to the figure."""

    model_config = ConfigDict(use_enum_values=True)

    path: Optional[str] = Field(default=None, description="File path or URL")
    type: TrackType = Field(default=TrackType.UNKNOWN, description="Inferred or specified track type")
    title: Optional[str] = Field(default=None, description="Display title")
    name: Optional[str] = Field(default=None, description="Unique identifier for group references (uses title if absent)")
    group: Optional[str] = Field(default=None, description="Group ID for shared scaling/coloring")
    style: Optional[str] = Field(default=None, description="Track-specific style (e.g., 'fill', 'outline')")
    color: Optional[str] = Field(default=None, description="Color specification")
    height: float = Field(default=1.0, description="Relative height of track")
    options: dict[str, Any] = Field(default_factory=dict, description="Advanced/track-specific settings")

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict, excluding empty values."""
        result: dict[str, Any] = {
            "type": self.type,
        }
        if self.path:
            result["path"] = self.path
        if self.title:
            result["title"] = self.title
        if self.name:
            result["name"] = self.name
        if self.group:
            result["group"] = self.group
        if self.style:
            result["style"] = self.style
        if self.color:
            result["color"] = self.color
        if self.height != 1.0:
            result["height"] = self.height
        if self.options:
            result["options"] = self.options
        return result


class GuideSpec(BaseModel):
    """Optional guides to include in the figure."""

    genes: bool = Field(default=False, description="Add gene annotation track")
    axis: bool = Field(default=True, description="Add genomic axis")
    scalebar: bool = Field(default=True, description="Add scale bar")


class GroupSpec(BaseModel):
    """
    Specification for a track group (shared scaling/coloring).

    Track references use track titles (or explicit names if set).
    The groups section is optional — tracks with a group field automatically
    get default behavior (autoscale=True, autocolor=True).
    Only include a GroupSpec entry when you need to override these defaults.
    """

    name: str = Field(description="Group identifier")
    tracks: list[str] = Field(default_factory=list, description="Track titles or names in this group")
    autoscale: bool = Field(default=True, description="Share y-axis scaling")
    autocolor: bool = Field(default=True, description="Share color palette")


class Template(BaseModel):
    """
    Root template specification for a genomic figure.

    Represents all information needed to generate a plot, designed to be:
    - Human-readable and editable
    - Stable across validation and rendering
    - Minimal, containing only user-relevant configuration
    """

    tracks: list[TrackSpec] = Field(default_factory=list)
    groups: list[GroupSpec] = Field(default_factory=list)
    guides: GuideSpec = Field(default_factory=GuideSpec)

    genome: Optional[str] = Field(default=None, description="Default genome (e.g., 'hg38', 'mm10')")
    width: float = Field(default=12.0, description="Figure width in inches")
    track_height: float = Field(default=1.0, description="Default track height")

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict, excluding private fields."""
        result: dict[str, Any] = {}

        if self.genome:
            result["genome"] = self.genome
        if self.width != 12.0:
            result["width"] = self.width
        if self.track_height != 1.0:
            result["track_height"] = self.track_height

        # Guides — only serialise non-default values
        guides_dict: dict[str, Any] = {}
        if self.guides.genes:
            guides_dict["genes"] = True
        if not self.guides.axis:
            guides_dict["axis"] = False
        if not self.guides.scalebar:
            guides_dict["scalebar"] = False
        if guides_dict:
            result["guides"] = guides_dict

        if self.tracks:
            result["tracks"] = [track.to_dict() for track in self.tracks]

        # Groups — only serialise entries that override defaults (autoscale or autocolor non-default)
        non_default_groups = [g for g in self.groups if not g.autoscale or not g.autocolor]
        if non_default_groups:
            result["groups"] = [
                {
                    "name": group.name,
                    **({"tracks": group.tracks} if group.tracks else {}),
                    **({"autoscale": group.autoscale} if not group.autoscale else {}),
                    **({"autocolor": group.autocolor} if not group.autocolor else {}),
                }
                for group in non_default_groups
            ]

        return result

    def to_yaml(self, header_args: Optional[str] = None) -> str:
        """Serialize template to YAML string with optional comment header."""
        body = yaml.dump(
            self.to_dict(),
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            indent=2,
        )
        if header_args is not None:
            header = (
                f"# PlotNado template\n"
                f"# Generated: plotnado init {header_args}\n"
                f"# Edit track titles, colors, and heights as needed.\n"
                f"# Plot a region: plotnado plot <this-file> --region chr1:1M-2M\n\n"
            )
            return header + body
        return body

    def save(self, path: str | Path, header_args: Optional[str] = None) -> None:
        """Save template to a YAML file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(self.to_yaml(header_args=header_args))

    @classmethod
    def load(cls, path: str | Path) -> "Template":
        """Load template from a YAML file."""
        with open(path, "r") as f:
            data = yaml.safe_load(f)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid template: expected dict, got {type(data)}")

        guides_data = data.get("guides", {})
        guides = GuideSpec(
            genes=guides_data.get("genes", False),
            axis=guides_data.get("axis", True),
            scalebar=guides_data.get("scalebar", True),
        )

        tracks = [
            TrackSpec(
                path=track_data.get("path"),
                type=TrackType(track_data.get("type", "unknown")),
                title=track_data.get("title"),
                name=track_data.get("name"),
                group=track_data.get("group"),
                style=track_data.get("style"),
                color=track_data.get("color"),
                height=track_data.get("height", 1.0),
                options=track_data.get("options", {}),
            )
            for track_data in data.get("tracks", [])
        ]

        groups = [
            GroupSpec(
                name=group_data["name"],
                tracks=group_data.get("tracks", []),
                autoscale=group_data.get("autoscale", True),
                autocolor=group_data.get("autocolor", True),
            )
            for group_data in data.get("groups", [])
        ]

        return cls(
            genome=data.get("genome"),
            width=data.get("width", 12.0),
            track_height=data.get("track_height", 1.0),
            guides=guides,
            tracks=tracks,
            groups=groups,
        )
